#!/usr/bin/env bash

set -eu

hook_name=$(basename "$0")

git_dir=$(git rev-parse --git-dir)
if [ -f "$git_dir/hooks/$hook_name" ]; then
  "$git_dir/hooks/$hook_name" "$@"
fi

shopt -s nullglob
HOOKS_DIR="$(dirname "$0")/$hook_name.d"
for hook in "$HOOKS_DIR"/*; do
  "$hook" "$@"
done
